#!/bin/bash
#Requires: aws cli, docker, docker-machine, docker-compose
log() {
  echo -e "  \e[33m$@\e[39m"
}
abort() {
  log $@
  exit 1
}

DIRNAME=$(dirname ${BASH_SOURCE[0]})

checkvar() {
  local name=$1
  local var=$2
  local default=$3
  if [[ -z "${!var}" ]]; then
    if [[ -n "$default" ]]; then
      eval "$var=$default"
    else
      log "must set $var"
      exit 1
    fi
  fi
  log "$name: ${!var}"
}

checkvar "Machine Path" "MACHINE_PATH"
if [[ -n "$AWS_PROFILE" ]]; then
  checkvar "AWS Profile" "AWS_PROFILE"
  AWS_DEFAULT_PROFILE=$AWS_PROFILE
else
  checkvar "AWS Access Key ID" "AWS_ACCESS_KEY_ID"
  checkvar "AWS Secret Access Key" "AWS_SECRET_ACCESS_KEY"
fi
checkvar "AWS Region" "AWS_REGION" "us-east-1"
AWS_DEFAULT_REGION=$AWS_REGION
checkvar "Server Name" "SERVER_NAME" #apps1
checkvar "Environment" "ENVIRONMENT" #prod
checkvar "Instance" "INSTANCE_TYPE" "t2.medium"
checkvar "Size" "SIZE" 20
if [[ -n "$VPC_ID" ]]; then
  checkvar "VPC" "VPC_ID"
  checkvar "Security Group" "SECURITY_GROUP"
  checkvar "Subnet" "SUBNET_ID"
  checkvar "Zone" "ZONE"
else
  log "VPC: auto generated"
fi
checkvar "Log Access Key" "LOG_ACCESS_KEY"
checkvar "Log Secret Key" "LOG_SECRET_KEY"
if [[ -n "$LOAD_BALANCER" ]]; then
  log "Load Balancer: Yes"
else
  log "Load Balancer: No"
fi
if [[ -n "$AUTO_DEPLOY" ]]; then
  log "Auto Deploy: Yes"
  checkvar "Github User" "GH_USER"
  checkvar "Github Token" "GH_TOKEN"
  checkvar "Deploy Whitelist" "DEPLOY_WHITELIST"
  checkvar "Deploy Secret" "DEPLOY_SECRET"
  checkvar "NODE_ENV" "NODE_ENV"
  checkvar "Domain" "DOMAIN"
else
  log "Auto Deploy: No"
fi
if [[ -n "$MONGO" ]]; then
  log "Mongo: Yes"
else
  log "Mongo: No"
fi
if [[ -n "$LETSENCRYPT" ]]; then
  log "Lets Encrypt: Yes"
else
  log "Lets Encrypt: No"
fi

FULL_NAME=${ENVIRONMENT}-${SERVER_NAME}
log "Full Server Name: $FULL_NAME"

if [[ -n "$DEBUG" ]]; then
  log "debug mode. stopping"
  exit 0
fi

read -p "Are you sure? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  exit 1
fi

create_log_group() {
  local name=$1
  local out=$(aws logs describe-log-groups --log-group-name-prefix $name --output text)
  if [[ -z "$out" ]]; then
    log "Creating Log Group: $name"
    aws logs create-log-group --log-group-name $name
    test $? -eq 0 || abort "create log group failed"
  fi
}

create_log_group $ENVIRONMENT
#TODO: create app metrics

if [[ -n "$LOAD_BALANCER" ]]; then
  create_log_group $ENVIRONMENT-nginx
  #TODO: create load balancer metrics
fi

out=$(docker-machine -s $MACHINE_PATH ls | grep $FULL_NAME)
if [[ "$?" == 1 ]]; then
  log "Creating EC2 Instance"
  #TODO: make this better
  if [[ -n "$VPC_ID" ]]; then
    docker-machine -s $MACHINE_PATH create \
      --driver amazonec2 \
      --amazonec2-root-size $SIZE \
      --amazonec2-region $AWS_REGION \
      --amazonec2-instance-type $INSTANCE_TYPE \
      --amazonec2-vpc-id $VPC_ID \
      --amazonec2-zone $ZONE \
      --amazonec2-subnet-id $SUBNET_ID \
      --amazonec2-security-group $SECURITY_GROUP \
      --engine-env "AWS_ACCESS_KEY_ID=$LOG_ACCESS_KEY" \
      --engine-env "AWS_SECRET_ACCESS_KEY=$LOG_SECRET_KEY" \
      --engine-env "AWS_DEFAULT_REGION=$AWS_REGION" \
      --engine-opt "log-driver=awslogs" \
      --engine-opt "log-opt awslogs-group=$ENVIRONMENT" \
      $FULL_NAME
  else
    docker-machine -s $MACHINE_PATH create \
      --driver amazonec2 \
      --amazonec2-root-size $SIZE \
      --amazonec2-region $AWS_REGION \
      --amazonec2-instance-type $INSTANCE_TYPE \
      --engine-env "AWS_ACCESS_KEY_ID=$LOG_ACCESS_KEY" \
      --engine-env "AWS_SECRET_ACCESS_KEY=$LOG_SECRET_KEY" \
      --engine-env "AWS_DEFAULT_REGION=$AWS_REGION" \
      --engine-opt "log-driver=awslogs" \
      --engine-opt "log-opt awslogs-group=$ENVIRONMENT" \
      $FULL_NAME
  fi
  test $? -eq 0 || abort "docker-machine failed"

  log "Installing htop"
  docker-machine -s $MACHINE_PATH ssh $FULL_NAME "sudo apt-get install -y htop"

  test $? -eq 0 || abort "htop install failed"
fi


eval $(docker-machine -s $MACHINE_PATH env $FULL_NAME)
test $? -eq 0 || abort "failed to set env"

#TODO download compose from github
compose() {
  cmd=$@
  SERVER_NAME=$SERVER_NAME \
    ENVIRONMENT=$ENVIRONMENT \
    DEPLOY_SECRET=$DEPLOY_SECRET \
    DOMAIN=$DOMAIN \
    GH_TOKEN=$GH_TOKEN \
    GH_USER=$GH_USER \
    NODE_ENV=$NODE_ENV \
    AWS_REGION=$AWS_REGION \
    docker-compose -f $DIRNAME/docker-compose.yml $@
}
compose pull
test $? -eq 0 || abort "compose pull failed"

if [[ -n "$LOAD_BALANCER" ]]; then
  log "Setting up load balancer"
  compose up -d dockergen
  test $? -eq 0 || abort "setting up dockergen failed"
  compose up -d nginx
  test $? -eq 0 || abort "setting up nginx failed"
fi

if [[ -n "$LETSENCRYPT" ]]; then
  log "Setting up lets encrypt"
  compose up -d letsencrypt
  test $? -eq 0 || abort "setting up lets encrypt failed"
fi

if [[ -n "$AUTO_DEPLOY" ]]; then
  log "Setting up deploy"
  compose up -d deploy
  test $? -eq 0 || abort "setting up deploy failed"
fi

if [[ -n "$MONGO" ]]; then
  out=$(docker inspect --type container mongo)
  if [[ "$?" == 1 ]]; then
    log "Setting up mongo"
    docker run \
      -d \
      -v /data/db:/data/db \
      --log-driver awslogs \
      --log-opt awslogs-group=$ENVIRONMENT \
      --log-opt awslogs-stream=mongo \
      --restart=always \
      -p 27017:27017 \
      --name mongo \
      mongo --storageEngine wiredTiger
    test $? -eq 0 || abort "creating mongo failed"
  fi
fi

log "Getting Public DNS"
aws ec2 describe-instances --filters Name=tag:Name,Values="$FULL_NAME" --query "Reservations[].Instances[].PublicDnsName" --output text
