nginx:
  container_name: 'nginx'
  image: 'firstandthird/nginx'
  restart: 'always'
  log_driver: 'awslogs'
  log_opt:
    awslogs-region: '${AWS_REGION}'
    awslogs-group: '${ENVIRONMENT}-nginx'
    awslogs-stream: '${SERVER_NAME}-nginx'
  volumes:
    - '/etc/nginx/conf.d'
    - '/etc/certs:/etc/nginx/certs:ro'
    - '/usr/share/nginx/html'
    - '/etc/nginx/vhost.d'
  ports:
    - '80:80'
    - '443:443'
dockergen:
  container_name: 'docker-gen'
  image: 'firstandthird/nginx-gen:0.0.2'
  restart: 'always'
  log_driver: 'awslogs'
  log_opt:
    awslogs-region: '${AWS_REGION}'
    awslogs-group: '${ENVIRONMENT}'
    awslogs-stream: '${SERVER_NAME}-docker-gen'
  volumes_from:
    - 'nginx'
  volumes:
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
letsencrypt:
  image: 'jrcs/letsencrypt-nginx-proxy-companion'
  container_name: 'letsencrypt'
  log_driver: 'awslogs'
  log_opt:
    awslogs-region: '${AWS_REGION}'
    awslogs-group: '${ENVIRONMENT}'
    awslogs-stream: '${SERVER_NAME}-letsencrypt'
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock:ro'
    - '/etc/certs/:/etc/nginx/certs:rw'
  volumes_from:
    - 'nginx'
  environment:
    NGINX_DOCKER_GEN_CONTAINER: 'docker-gen'
    #DEBUG: 'true'
deploy:
  container_name: 'deploy'
  image: 'shipment/deploy:0.0.8'
  restart: 'always'
  environment:
    VIRTUAL_HOST: 'deploy.${DOMAIN}'
    ROOT_HOST: '${DOMAIN}'
    NODE_ENV: '${NODE_ENV}'
    GH_USERNAME: '${GH_USER}'
    GH_TOKEN: '${GH_TOKEN}'
    SECRET: '${DEPLOY_SECRET}'
    ENVIRONMENT: '${ENVIRONMENT}'
    SERVER_NAME: '${SERVER_NAME}'
  log_driver: 'awslogs'
  log_opt:
    awslogs-region: '${AWS_REGION}'
    awslogs-group: '${ENVIRONMENT}'
    awslogs-stream: '${SERVER_NAME}-deploy'
  ports:
    - '5000'
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
