#!/bin/bash

#DEBUG=1
MACHINE_PATH=$PWD/machines
AWS_ACCESS_KEY_ID="123"
AWS_SECRET_ACCESS_KEY="123"
AWS_REGION="us-west-2"
INSTANCE_TYPE="t2.small"
ENVIRONMENT="production"
SERVER_NAME="apps1"
LOG_ACCESS_KEY="123"
LOG_SECRET_KEY="123"
LOAD_BALANCER=1
MONGO=1

source ~/path/to/provision-aws/create-server

